version: "3.3"
   
services:
  app:
    build:
        context: .
    volumes:
      - ./src:/src/
    ports:
      - 8501:8501  
    command: "streamlit run /src/fc_poc.py"
  
  devbox:
    build:
        context: .
    volumes:
      - ./src:/src/
    command: "/bin/zsh"
